"""
Week 4 - Part D: Streaming Responses
Demonstrates real-time token streaming vs waiting for complete responses.
"""

import time
import sys

def simulate_streaming_output(text: str):
    print("=== Streaming Response Demo ===")
    print("AI Response: ", end="", flush=True)
    for word in text.split(" "):
        print(word + " ", end="", flush=True)
        time.sleep(0.06)
    print("\n\n[Streaming complete]")

if __name__ == "__main__":
    sample_response = "Streaming allows applications to render tokens immediately as they are generated by the LLM, dramatically reducing perceived latency for interactive interfaces like chatbots."
    simulate_streaming_output(sample_response)
